apiVersion: v1
kind: Pod
metadata:
  name: cyborg-seeder-finals-cromu00057
  labels:
    type: cyborg-seeder
spec:  # specification of the pod's contents
  restartPolicy: Never #OnFailure

  imagePullSecrets:
  - name: ucsbseclab-dockerhub

  volumes:
  - name: cyborg-results
    persistentVolumeClaim:
      claimName: cyborg-results

  containers:
  - name: cyborg-seeder-finals-cromu00057

    stdin: true
    tty: true

    image: "zardus/research:cyborg-generator"
    command: ["/bin/bash", "-c", "python /home/angr/cyborg-generator/kubernetes_seeder.py finals CROMU_00057 3600 6"]

    imagePullPolicy: Always

    volumeMounts:
     - name: cyborg-results
       mountPath: "/results"

    resources:
      limits:
        cpu: 1
        memory: 10Gi
      requests:
        cpu: 1
        memory: 10Gi
