apiVersion: v1
kind: Pod
metadata:
  name: cyborg-seeker-qualifiers-kprca00037-pov0
  labels:
    type: cyborg-seeker
spec:  # specification of the pod's contents
  restartPolicy: Never #OnFailure

  imagePullSecrets:
  - name: ucsbseclab-dockerhub

  volumes:
  - name: cyborg-results
    persistentVolumeClaim:
      claimName: cyborg-results

  containers:
  - name: cyborg-seeker-qualifiers-kprca00037-pov0

    stdin: true
    tty: true

    image: "zardus/research:cyborg-generator"
    command: ["/bin/bash", "-c", "python /home/angr/cyborg-generator/kubernetes_seeker.py qualifiers KPRCA_00037 pov_0 3600"]

    imagePullPolicy: Always

    volumeMounts:
     - name: cyborg-results
       mountPath: "/results"

    resources:
      limits:
        cpu: 1
        memory: 10Gi
      requests:
        cpu: 1
        memory: 10Gi
